//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CommunityAssistEntities1 : DbContext
{
    public CommunityAssistEntities1()
        : base("name=CommunityAssistEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Donation> Donations { get; set; }
    public DbSet<Person> People { get; set; }
    public DbSet<ServiceGrant> ServiceGrants { get; set; }
}
